version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
  disable:
    - gosec

linters-settings:
  errcheck:
    exclude-functions:
      - (testing.TB).Logf
      - (testing.TB).Log
